### ISSUE TITLE
Item entity 6360 has no item?!

### ISSUE THREAD

**Issue by StatywPlay** [MFCgaming/SuperLuckyBlock#2]
After break [Server thread/ERROR]: Item entity 6360 has no item?! spamming in console

same
 [Server thread/ERROR]: Item entity 7149 has no item?! spamming in console

**Comment by MFCgaming** [comment]
Hmm... I go fix this. Thanks for report

**Comment by MFCgaming** [comment]
@StatywPlay Install clearlagg and do /remove items -1 Then restart server and break a sponge. Is it spanning again?

**Comment by StatywPlay** [comment]
its not for all sponges its sometimes

**Comment by MFCgaming** [comment]
I know the issues now i go fix it

**Comment by MFCgaming** [comment]
Fixed hopefully of happens again please create a new issues

**Comment by MFCgaming** [comment]
Bug isn't fixed!
